# Generated by Django 5.2.8 on 2025-12-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gatimu School', max_length=100)),
                ('overview', models.TextField()),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'School Info',
            },
        ),
    ]
