# Generated by Django 5.2.8 on 2025-12-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_schoolinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolinfo',
            name='overview',
        ),
    ]
