# Generated by Django 6.0 on 2025-12-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_schoolinfo_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
